Ns orderform
nss-evening-cohort-19/pos-system-team-5-alive pull request #54
Opened 2022-06-18 16:59 UTC by NickScrimale

2022-06-18 17:12 UTC, scamp925 requested changes
- [x] When submit btn on Create an Order form is clicked, nothing happens
- [ ] clearDom needs to be updated to clear out main-header, order-div, and form-container, so that those divs don't render at the same time

2022-06-18 19:30 UTC, TwoFivinClimber requested changes
!Important! - Order details button needed that passes orderId to order details function. 
Field in create order form need to all be required.
Edit form doesn't populate with phone or order type (existing data).
When order is deleted, empty order message shows.

2022-06-21 00:09 UTC, TwoFivinClimber approved these changes

2022-06-21 00:10 UTC, scamp925 approved these changes

2022-06-21 00:15 UTC, merged